# Generated by Django 3.0 on 2024-02-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workname', models.CharField(choices=[('close', 'ปิด'), ('active', 'กำลังดำเนินการ'), ('succeed', 'สำเร็จ')], default='close', max_length=200)),
            ],
        ),
    ]
