# Generated by Django 5.0.4 on 2024-04-25 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_userprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivityhistory',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='useractivityhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tasking',
        ),
        migrations.DeleteModel(
            name='UserActivityHistory',
        ),
    ]
