# Generated by Django 5.0.4 on 2024-05-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_remove_task_clicked_date_remove_task_user_clicked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickhistory',
            name='status',
            field=models.CharField(choices=[('proceed', 'Proceed'), ('success', 'Success')], default='proceed', max_length=10),
        ),
    ]
