# Generated by Django 5.0.4 on 2024-05-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_clickhistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickhistory',
            name='status',
            field=models.CharField(blank=True, choices=[('', '-------'), ('proceed', 'Proceed'), ('success', 'Success')], max_length=10, null=True),
        ),
    ]
