# Generated by Django 5.0.4 on 2024-05-21 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
    ]
