from django.urls import path
from .views import HomePage, HomememPage, Register, Reserve, EditProfile, del_product ,user_products, user_reservations, cancel_reservation, user_work_report, dashboard, manage_users, manage_groups, manage_reservations, manage_products, user_add, user_edit, user_delete, group_add, group_edit, group_delete, reservation_delete, product_add, product_edit, product_delete
from . import views

urlpatterns = [
    path('', HomePage, name='HomePage'),
    path('member/', HomememPage, name='HomememPage' ),
    path('member/<int:user_id>/', views.member_detail, name='member_detail'),  
    path('register/', Register, name='Register' ),
    path('edit-profile/', EditProfile, name='EditProfile'),
    path('tasking/', views.tasking_list, name='tasking_list'),  
    path('add_task/', views.add_task, name='add_task'),
    path('proceed_task/<int:task_id>/', views.proceed_task, name='proceed_task'),
    path('success_task/<int:task_id>/', views.success_task, name='success_task'),
    path('work_report/', views.work_report, name='work_report'),
    path('user_work_report/', user_work_report, name='user_work_report'),
    path('reserve/', Reserve, name='Reserve'),
    path('add_product/', views.add_product, name='add_product'),
    path('del_product/<int:product_id>/', del_product, name='del_product'),
    path('user_products/', user_products, name='user_products'),
    path('conreserve/', views.Conreserve, name='conreserve'),
    path('user_reservations/', user_reservations, name='user_reservations'),
    path('cancel_reservation/<int:reservation_id>/', cancel_reservation, name='cancel_reservation'),
    path('reservation_report/', views.reservation_report, name='reservation_report'),
    path('user_reservation_report/', views.user_reservation_report, name='user_reservation_report'),
    path('reservation_list/', views.reservation_list, name='reservation_list'),
    path('groups/', views.group_list, name='group_list'),
    path('groups/new/', views.group_create, name='group_create'),
    path('groups/edit/<int:pk>/', views.group_update, name='group_update'),
    path('groups/delete/<int:pk>/', views.group_delete, name='group_delete'),
    path('groups/edit/<int:group_pk>/remove_member/<int:member_pk>/', views.remove_member, name='remove_member'),
    path('groups/edit/<int:group_pk>/make_leader/<int:member_pk>/', views.make_leader, name='make_leader'),
    
    path('dashboard/', dashboard, name='dashboard'),
    path('manage_users/', manage_users, name='manage_users'),
    path('user_add/', user_add, name='user_add'),
    path('user_edit/<int:pk>/', user_edit, name='user_edit'),
    path('user_delete/<int:pk>/', user_delete, name='user_delete'),
    path('manage_groups/', manage_groups, name='manage_groups'),
    path('group_add/', group_add, name='group_add'),
    path('group_edit/<int:pk>/', group_edit, name='group_edit'),
    path('group_delete/<int:pk>/', group_delete, name='group_delete'),
    path('manage_products/', manage_products, name='manage_products'),
    path('product_add/', product_add, name='product_add'),
    path('product_edit/<int:pk>/', product_edit, name='product_edit'),
    path('product_delete/<int:pk>/', product_delete, name='product_delete'),
    path('manage_reservations/', manage_reservations, name='manage_reservations'),
    path('reservation_delete/<int:pk>/', reservation_delete, name='reservation_delete'),
]